/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DataRouteImport } from './routes/data'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as PlanningRouteImport } from './routes/planning'
import { Route as PriorityRouteImport } from './routes/priority'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as WhatIfRouteImport } from './routes/what-if'
import { Route as AssetsIndexRouteImport } from './routes/assets/index'
import { Route as AssetsAssetIdRouteImport } from './routes/assets/$assetId'
import { Route as RequestsIndexRouteImport } from './routes/requests/index'
import { Route as RequestsRequestIdRouteImport } from './routes/requests/$requestId'
import { Route as RequestsNewRouteImport } from './routes/requests/new'
import { Route as RisksIndexRouteImport } from './routes/risks/index'
import { Route as RisksAssetIdRouteImport } from './routes/risks/$assetId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRoute = DataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanningRoute = PlanningRouteImport.update({
  id: '/planning',
  path: '/planning',
  getParentRoute: () => rootRouteImport,
} as any)
const PriorityRoute = PriorityRouteImport.update({
  id: '/priority',
  path: '/priority',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatIfRoute = WhatIfRouteImport.update({
  id: '/what-if',
  path: '/what-if',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsIndexRoute = AssetsIndexRouteImport.update({
  id: '/assets/',
  path: '/assets/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsAssetIdRoute = AssetsAssetIdRouteImport.update({
  id: '/assets/$assetId',
  path: '/assets/$assetId',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsIndexRoute = RequestsIndexRouteImport.update({
  id: '/requests/',
  path: '/requests/',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsRequestIdRoute = RequestsRequestIdRouteImport.update({
  id: '/requests/$requestId',
  path: '/requests/$requestId',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsNewRoute = RequestsNewRouteImport.update({
  id: '/requests/new',
  path: '/requests/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RisksIndexRoute = RisksIndexRouteImport.update({
  id: '/risks/',
  path: '/risks/',
  getParentRoute: () => rootRouteImport,
} as any)
const RisksAssetIdRoute = RisksAssetIdRouteImport.update({
  id: '/risks/$assetId',
  path: '/risks/$assetId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/data': typeof DataRoute
  '/impact': typeof ImpactRoute
  '/plan': typeof PlanRoute
  '/planning': typeof PlanningRoute
  '/priority': typeof PriorityRoute
  '/tasks': typeof TasksRoute
  '/what-if': typeof WhatIfRoute
  '/assets/$assetId': typeof AssetsAssetIdRoute
  '/requests/$requestId': typeof RequestsRequestIdRoute
  '/requests/new': typeof RequestsNewRoute
  '/risks/$assetId': typeof RisksAssetIdRoute
  '/assets/': typeof AssetsIndexRoute
  '/requests/': typeof RequestsIndexRoute
  '/risks/': typeof RisksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/data': typeof DataRoute
  '/impact': typeof ImpactRoute
  '/plan': typeof PlanRoute
  '/planning': typeof PlanningRoute
  '/priority': typeof PriorityRoute
  '/tasks': typeof TasksRoute
  '/what-if': typeof WhatIfRoute
  '/assets/$assetId': typeof AssetsAssetIdRoute
  '/requests/$requestId': typeof RequestsRequestIdRoute
  '/requests/new': typeof RequestsNewRoute
  '/risks/$assetId': typeof RisksAssetIdRoute
  '/assets': typeof AssetsIndexRoute
  '/requests': typeof RequestsIndexRoute
  '/risks': typeof RisksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/data': typeof DataRoute
  '/impact': typeof ImpactRoute
  '/plan': typeof PlanRoute
  '/planning': typeof PlanningRoute
  '/priority': typeof PriorityRoute
  '/tasks': typeof TasksRoute
  '/what-if': typeof WhatIfRoute
  '/assets/$assetId': typeof AssetsAssetIdRoute
  '/requests/$requestId': typeof RequestsRequestIdRoute
  '/requests/new': typeof RequestsNewRoute
  '/risks/$assetId': typeof RisksAssetIdRoute
  '/assets/': typeof AssetsIndexRoute
  '/requests/': typeof RequestsIndexRoute
  '/risks/': typeof RisksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dashboard'
    | '/data'
    | '/impact'
    | '/plan'
    | '/planning'
    | '/priority'
    | '/tasks'
    | '/what-if'
    | '/assets/$assetId'
    | '/requests/$requestId'
    | '/requests/new'
    | '/risks/$assetId'
    | '/assets/'
    | '/requests/'
    | '/risks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/dashboard'
    | '/data'
    | '/impact'
    | '/plan'
    | '/planning'
    | '/priority'
    | '/tasks'
    | '/what-if'
    | '/assets/$assetId'
    | '/requests/$requestId'
    | '/requests/new'
    | '/risks/$assetId'
    | '/assets'
    | '/requests'
    | '/risks'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/dashboard'
    | '/data'
    | '/impact'
    | '/plan'
    | '/planning'
    | '/priority'
    | '/tasks'
    | '/what-if'
    | '/assets/$assetId'
    | '/requests/$requestId'
    | '/requests/new'
    | '/risks/$assetId'
    | '/assets/'
    | '/requests/'
    | '/risks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DashboardRoute: typeof DashboardRoute
  DataRoute: typeof DataRoute
  ImpactRoute: typeof ImpactRoute
  PlanRoute: typeof PlanRoute
  PlanningRoute: typeof PlanningRoute
  PriorityRoute: typeof PriorityRoute
  TasksRoute: typeof TasksRoute
  WhatIfRoute: typeof WhatIfRoute
  AssetsAssetIdRoute: typeof AssetsAssetIdRoute
  RequestsRequestIdRoute: typeof RequestsRequestIdRoute
  RequestsNewRoute: typeof RequestsNewRoute
  RisksAssetIdRoute: typeof RisksAssetIdRoute
  AssetsIndexRoute: typeof AssetsIndexRoute
  RequestsIndexRoute: typeof RequestsIndexRoute
  RisksIndexRoute: typeof RisksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data': {
      id: '/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planning': {
      id: '/planning'
      path: '/planning'
      fullPath: '/planning'
      preLoaderRoute: typeof PlanningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/priority': {
      id: '/priority'
      path: '/priority'
      fullPath: '/priority'
      preLoaderRoute: typeof PriorityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/what-if': {
      id: '/what-if'
      path: '/what-if'
      fullPath: '/what-if'
      preLoaderRoute: typeof WhatIfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets/': {
      id: '/assets/'
      path: '/assets'
      fullPath: '/assets/'
      preLoaderRoute: typeof AssetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets/$assetId': {
      id: '/assets/$assetId'
      path: '/assets/$assetId'
      fullPath: '/assets/$assetId'
      preLoaderRoute: typeof AssetsAssetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/': {
      id: '/requests/'
      path: '/requests'
      fullPath: '/requests/'
      preLoaderRoute: typeof RequestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/$requestId': {
      id: '/requests/$requestId'
      path: '/requests/$requestId'
      fullPath: '/requests/$requestId'
      preLoaderRoute: typeof RequestsRequestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/new': {
      id: '/requests/new'
      path: '/requests/new'
      fullPath: '/requests/new'
      preLoaderRoute: typeof RequestsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risks/': {
      id: '/risks/'
      path: '/risks'
      fullPath: '/risks/'
      preLoaderRoute: typeof RisksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risks/$assetId': {
      id: '/risks/$assetId'
      path: '/risks/$assetId'
      fullPath: '/risks/$assetId'
      preLoaderRoute: typeof RisksAssetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DashboardRoute: DashboardRoute,
  DataRoute: DataRoute,
  ImpactRoute: ImpactRoute,
  PlanRoute: PlanRoute,
  PlanningRoute: PlanningRoute,
  PriorityRoute: PriorityRoute,
  TasksRoute: TasksRoute,
  WhatIfRoute: WhatIfRoute,
  AssetsAssetIdRoute: AssetsAssetIdRoute,
  RequestsRequestIdRoute: RequestsRequestIdRoute,
  RequestsNewRoute: RequestsNewRoute,
  RisksAssetIdRoute: RisksAssetIdRoute,
  AssetsIndexRoute: AssetsIndexRoute,
  RequestsIndexRoute: RequestsIndexRoute,
  RisksIndexRoute: RisksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
